fixes #211
thomaspoignant/scim-patch pull request #212
Opened 2022-03-16 10:56 UTC by asutosh97

# Description

### What was the problem
Refer #211 

### How is it resolved?

# Changes include
- [x] Bugfix (non-breaking change that solves an issue)

# Closes issue(s)
Resolve #211 

# Checklist
- [x] I have tested this code
- [x] I have added unit test to cover this code
- [x] I have updated the Readme
- [x] I have followed the [contributing guide](CONTRIBUTING.md)

2022-03-21 15:29 UTC, thomaspoignant requested changes

2022-03-22 07:59 UTC, asutosh97 commented on test/scimPatch.test.ts
> +            console.log(JSON.stringify(afterPatch));
oops, missed it 😅

2022-03-22 08:24 UTC, asutosh97 commented on src/scimPatch.ts
> +                return false;
Yup, I agree with you.
It does the job, but like you said, doesn't respect the contract, hence affects the readability as well, will take more effort to understand while reading. It kind of takes the advantage of the `any` return type of the function.

How about we make the return type `Record<string, unknown>`?

2022-03-23 09:15 UTC, thomaspoignant approved these changes

2022-03-23 09:16 UTC, merged

2022-03-23 09:28 UTC, thomaspoignant commented
@asutosh97 the new version is released.